services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: vault-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  postgres:
    image: postgres:15
    container_name: vault-postgres
    environment:
      POSTGRES_USER: vault_user
      POSTGRES_PASSWORD: vault_password
      POSTGRES_DB: vault_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  elastic_data:
  postgres_data:
